servers:
- id: chain1
  mu: 5.27253214380333
  queue_type: FIFO
  lambda: 2.0076164935244005
  Cost: 14899.8
  Jobs: 2818
  Avg_queue_time: 0.205557
  Avg_service_time: 0.187578
  Utilization: 0.528594
- id: chain2
  mu: 5.83754313849087
  queue_type: PS
  Cost: 18038.5
  Jobs: 613
  Avg_queue_time: 0.0109543
  Avg_service_time: 0.162924
  Utilization: 0.0998724
- id: chain3
  mu: 4.549136880106992
  queue_type: FIFO
  Cost: 11347.3
  Jobs: 186
  Avg_queue_time: 0.00526057
  Avg_service_time: 0.223484
  Utilization: 0.041568
- id: chain4
  mu: 8.123987347260954
  queue_type: PS
  Cost: 33999.6
  Jobs: 853
  Avg_queue_time: 0.0118444
  Avg_service_time: 0.118478
  Utilization: 0.101062
- id: chain1_p
  mu: 3.777430788663129
  queue_type: PS
  lambda: 0.6286495783772643
transitions:
- from: chain1
  to: exit
  probability: 0.51314919
- from: chain1
  to: chain2
  probability: 0.19733961
- from: chain1
  to: chain4
  probability: 0.28951121
- from: chain2
  to: exit
  probability: 0.60764847
- from: chain2
  to: chain3
  probability: 0.29762743
- from: chain2
  to: chain1
  probability: 0.07213599
- from: chain3
  to: exit
  probability: 0.62843463
- from: chain3
  to: chain2
  probability: 0.10162645
- from: chain3
  to: chain1
  probability: 0.14505519
- from: chain3
  to: chain4
  probability: 0.07946227
- from: chain4
  to: exit
  probability: 0.80167347
- from: chain4
  to: chain1
  probability: 0.11558537
- from: chain4
  to: chain2
  probability: 0.04654765
- from: chain2
  to: chain1_p
  probability: 0.02258811
- from: chain3
  to: chain1_p
  probability: 0.04542146
- from: chain4
  to: chain1_p
  probability: 0.03619351
- from: chain1_p
  to: exit
  probability: 0.51314919
- from: chain1_p
  to: chain2
  probability: 0.19733961
- from: chain1_p
  to: chain4
  probability: 0.28951121
